apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: hzhyvinskyi/iam-solutions-api-gateway:1.0.0
          env:
            - name: SERVICE_NAME
              value: "API Gateway"
            - name: SERVICE_HOSTNAME
              value: "api-gateway"
            - name: SERVICE_PORT
              value: "8081"
            - name: USER_SERVICE_REVERSE_PROXY_TCP_SOCKET_ADDRESS
              value: "user-service:8087"
